       0 TEST.FAR.DIRECTORY/
     112 TEST.FAR.DIRECTORY/d
     222 TEST.FAR.e
     292 TEST.FAR.DIRECTORY/b
     305 TEST.FAR.a
     740 TEST.FAR.DIRECTORY/c

       0 TEST.FAR.DIRECTORY/
     112 TEST.FAR.DIRECTORY/d
     222 TEST.FAR.e
     292 TEST.FAR.DIRECTORY/b
     305 TEST.FAR.a
     740 TEST.FAR.DIRECTORY/c

TEST.FAR.a
TEST.FAR.e

TEST.FAR.DIRECTORY:
b
c
d
