#!/bin/bash
# Torture: Operations on empty files

RUN="/usr/bin/valgrind -q"
FILES=/c/cs323/Hwk1/Tests/Files
LOCAL=TEST.FAR
ARKIV=$LOCAL.ARCHIVE

# Set collating sequence for sort
export LC_ALL=C

# Delete all files created when exiting
ALL="$ARKIV $LOCAL.a $LOCAL.b $LOCAL.c $LOCAL.d $LOCAL.e"
trap "/bin/chmod -f +rwx $ALL; /bin/rm -rf $ALL" 0 1 2 3 9 15

# Remove existing archive file
if test -e $ARKIV; then
  /bin/rm -rf $ARKIV
fi

# Create some local files
/bin/cp -f /dev/null $LOCAL.a
/bin/cp -f /dev/null $LOCAL.b
/bin/cp -f /dev/null $LOCAL.c
/bin/cp -f /dev/null $LOCAL.d

# Create nonexistent archive and add files; list to verify
$RUN ./Far r $ARKIV $LOCAL.a $LOCAL.b
$RUN ./Far t $ARKIV | sort
echo

# Add more files; list to verify
$RUN ./Far r $ARKIV $LOCAL.c $LOCAL.d
$RUN ./Far t $ARKIV | sort
echo

# Remove local files
/bin/rm -f $LOCAL.a $LOCAL.b $LOCAL.c $LOCAL.d

# Extract empty files from archive
$RUN ./Far x $ARKIV $LOCAL.a $LOCAL.b $LOCAL.c $LOCAL.d
$RUN ./Far t $ARKIV | sort

# Verify that extracted files are correct
/usr/bin/cmp -c /dev/null $LOCAL.a
/usr/bin/cmp -c /dev/null $LOCAL.b
/usr/bin/cmp -c /dev/null $LOCAL.c
/usr/bin/cmp -c /dev/null $LOCAL.d
