#!/bin/bash
# Torture: Prohibit storage leaks in replace

RUN="/usr/bin/valgrind -q"
FILES=/c/cs323/Hwk1/Tests/Files
LOCAL=TEST.FAR
ARKIV=$LOCAL.ARCHIVE
REACHABLE=/c/cs323/bin/reachable

# Set collating sequence for sort
export LC_ALL=C

# Delete all files created when exiting
ALL="$ARKIV $LOCAL.a $LOCAL.b $LOCAL.c $LOCAL.d $LOCAL.e"
trap "/bin/chmod -f +rwx $ALL; /bin/rm -rf $ALL" 0 1 2 3 9 15

# Remove existing archive file
if test -e $ARKIV; then
  /bin/rm -rf $ARKIV
fi

# Create nonexistent archive and add files; list to verify
$REACHABLE ./Far r $ARKIV $FILES/a $FILES/b $FILES/c $FILES/d $FILES/e
echo
$RUN ./Far t $ARKIV | sort
echo

# Remove A, B, C, and D; and create new versions of A and C
/bin/rm -f $LOCAL.a $LOCAL.b $LOCAL.c $LOCAL.d
/bin/cp -f $FILES/e $LOCAL.a
/bin/cp -f $FILES/f $LOCAL.c

# Replace all files in archive, inducing two errors
$REACHABLE ./Far r $ARKIV $LOCAL.a $LOCAL.b $LOCAL.c $LOCAL.d
echo

# List to verify archive is correct
$RUN ./Far t $ARKIV | sort
