#!/bin/bash
# size(-p 4 -m 13) << size(-m 13)?

RUN=/c/cs323/bin/run

EFLAG="-m 13 -p 4"
XFLAG="-m 13"
FILE=/bin/tcsh
FUDGE=80

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$
XOUT=/tmp/lzw.x.$USER.$$

trap "/bin/rm -f $EOUT $DOUT $XOUT" 0 1 2 3 9 15

$RUN ./encode $EFLAG < $FILE > $EOUT
$RUN ./decode        < $EOUT > $DOUT
/usr/bin/cmp - $FILE < $DOUT

#$RUN ./encode $XFLAG < $FILE > $XOUT
#$RUN ./decode        < $XOUT > $DOUT
#/usr/bin/cmp - $FILE < $DOUT

#ESIZE=`wc -c < $EOUT`
#XSIZE=`wc -c < $XOUT`
#BOUND=$(($FUDGE * $XSIZE / 100))

if test $ESIZE -gt $BOUND -o -n "$DEBUG_SCRIPT" ; then
  echo "size($EFLAG) = $ESIZE > $BOUND = .$FUDGE * $XSIZE = .$FUDGE * size($XFLAG)"
fi
