#!/bin/bash

# \ifdef: Name exists

/usr/bin/valgrind -q ./m15 <<END
\def{A}{aardvark}
\ifdef{A}{Output this text.}{Do not output this text.}
END

echo -----

# \if: Argument nonempty

/usr/bin/valgrind -q ./m15 <<END
\def{A}{aardvark}
\if{A}{Output this text.}{Do not output this text.}
END
