#!/bin/bash
# Redirect stdin to file (<)
# REQUIRES: REDIR (<)

FILES=
PROGS="wc"

RUN="/c/cs323/bin/run -wall=2"
trap "/bin/rm -f $FILES; \
      /usr/bin/killall -q -u $USER Bsh $PROGS 2>/dev/null" 0 1 2 3 9 15
ulimit -u 300

$RUN ./Bsh <<END
/usr/bin/wc -c < /c/cs323/Style/C-Pike
echo End of test
END

echo
