#!/bin/bash
# Multiple commands separated by ;
# REQUIRES: SEP (;)

FILES=
PROGS="echo"

RUN="/c/cs323/bin/run -wall=2"
trap "/bin/rm -f $FILES; \
      /usr/bin/killall -q -u $USER Bsh $PROGS 2>/dev/null" 0 1 2 3 9 15
ulimit -u 300

$RUN ./Bsh <<END
echo Garbage In, ; echo Garbage Out!
echo End of test
END

echo
