#!/bin/bash
# Simple background command
# REQUIRES: BG & BG-PID

ERROR="+Bsh.err.$$"

FILES="$ERROR"
PROGS="echo sleeper"

RUN="/c/cs323/bin/run -wall=2"
trap "/bin/rm -f $FILES; \
      /usr/bin/killall -q -u $USER Bsh $PROGS 2>/dev/null" 0 1 2 3 9 15
ulimit -u 300

$RUN ./Bsh <<END 2>$ERROR
echo As simple as
/c/cs323/Hwk5/Tests/sleeper alpha 0.4 gamma & sleep 0.2
echo beta
/usr/bin/sleep 0.4
echo End of test
END

echo

/c/cs323/Hwk5/Tests/suppress $ERROR
