#!/bin/bash
# Redirect stdin to group of simple commands
# REQUIRES: REDIR (<), SUBCMD

FILES=
PROGS="echo cat"

RUN="/c/cs323/bin/run -wall=2"
trap "/bin/rm -f $FILES; \
      /usr/bin/killall -q -u $USER Bsh $PROGS 2>/dev/null" 0 1 2 3 9 15
ulimit -u 300

$RUN ./Bsh <<END
( echo vvvvvvvv ; cat ; echo ^^^^^^^^ ) < /c/cs323/Hwk5/Tests/stk.txt
echo End of test
END

echo
