#!/bin/bash
# dirs
# REQUIRES: BUILT-IN (cd, dirs)

STRACE=+Bsh.strace.$$

FILES="$STRACE"
PROGS="echo"

RUN="/c/cs323/bin/run -wall=2"
trap "/bin/rm -f $FILES; \
      /usr/bin/killall -q -u $USER Bsh $PROGS 2>/dev/null" 0 1 2 3 9 15
ulimit -u 300

strace -f -o $STRACE -egetcwd,execve ./Bsh <<END
cd /c/cs323/Style
dirs
echo End of test
END

echo

grep pwd $STRACE
echo
