#!/bin/bash
# Simple cases of $?
# REQUIRES: STATUS

FILES=
PROGS="echo true printenv false"

RUN="/c/cs323/bin/run -wall=2"
trap "/bin/rm -f $FILES; \
      /usr/bin/killall -q -u $USER Bsh $PROGS 2>/dev/null" 0 1 2 3 9 15
ulimit -u 300

$RUN ./Bsh <<\END
echo In Bsh, true =
/usr/bin/true
/usr/bin/printenv ?
echo but false =
/usr/bin/false
/usr/bin/printenv ?
echo End of test
END

echo
